name: manywells
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24
  - pandas=1.5.3
  - matplotlib=3.7.2
  - seaborn=0.13.2
  - scikit-learn=1.3.0
  - pip
  - pip:
    - casadi==3.6.4
